// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"ai-gateway/config"
	"ai-gateway/internal/api/http"
	"ai-gateway/internal/api/http/handler"
	"ai-gateway/internal/repository"
	"ai-gateway/internal/repository/dao"
	"ai-gateway/internal/service/gateway"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitGinServerWithWire initializes the Gin HTTP server using Wire.
func InitGinServerWithWire(cfg *config.Config, logger *zap.Logger) *http.Server {
	db := provideDB(cfg, logger)
	providerDAO := dao.NewGormProviderDAO(db)
	providerRepository := repository.NewProviderRepository(providerDAO)
	routingRuleDAO := dao.NewGormRoutingRuleDAO(db)
	routingRuleRepository := repository.NewRoutingRuleRepository(routingRuleDAO)
	loadBalanceDAO := dao.NewGormLoadBalanceDAO(db)
	loadBalanceRepository := repository.NewLoadBalanceRepository(loadBalanceDAO)
	gatewayService := gateway.NewGatewayService(providerRepository, routingRuleRepository, loadBalanceRepository, logger)
	openAIHandler := handler.NewOpenAIHandler(gatewayService, logger)
	anthropicHandler := handler.NewAnthropicHandler(gatewayService, logger)
	adminHandler := provideAdminHandler()
	authConfig := provideAuthConfig(cfg)
	server := http.NewServer(openAIHandler, anthropicHandler, adminHandler, authConfig, logger)
	return server
}

// wire.go:

// provideDB handles the error from InitDB.
func provideDB(cfg *config.Config, logger *zap.Logger) *gorm.DB {
	db, err := InitDB(cfg, logger)
	if err != nil {
		logger.Fatal("failed to initialize database", zap.Error(err))
	}
	if db == nil {
		logger.Fatal("MySQL must be enabled")
	}
	return db
}

// provideAuthConfig extracts AuthConfig from Config.
func provideAuthConfig(cfg *config.Config) config.AuthConfig {
	return cfg.Auth
}

// provideAdminHandler provides nil AdminHandler (to be implemented later).
func provideAdminHandler() *handler.AdminHandler {
	return nil
}
