// Code generated by MockGen. DO NOT EDIT.
// Source: ai-gateway/internal/repository (interfaces: UserRepository,UsageLogRepository,APIKeyRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "ai-gateway/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(arg0 context.Context, arg1 *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), arg0, arg1)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(arg0 context.Context, arg1 string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", arg0, arg1)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(arg0 context.Context, arg1 int64) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), arg0, arg1)
}

// GetByUsername mocks base method.
func (m *MockUserRepository) GetByUsername(arg0 context.Context, arg1 string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", arg0, arg1)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserRepositoryMockRecorder) GetByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetByUsername), arg0, arg1)
}

// List mocks base method.
func (m *MockUserRepository) List(arg0 context.Context) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserRepositoryMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepository)(nil).List), arg0)
}

// Update mocks base method.
func (m *MockUserRepository) Update(arg0 context.Context, arg1 *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), arg0, arg1)
}

// MockUsageLogRepository is a mock of UsageLogRepository interface.
type MockUsageLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUsageLogRepositoryMockRecorder
}

// MockUsageLogRepositoryMockRecorder is the mock recorder for MockUsageLogRepository.
type MockUsageLogRepositoryMockRecorder struct {
	mock *MockUsageLogRepository
}

// NewMockUsageLogRepository creates a new mock instance.
func NewMockUsageLogRepository(ctrl *gomock.Controller) *MockUsageLogRepository {
	mock := &MockUsageLogRepository{ctrl: ctrl}
	mock.recorder = &MockUsageLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageLogRepository) EXPECT() *MockUsageLogRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUsageLogRepository) Create(arg0 context.Context, arg1 *domain.UsageLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUsageLogRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUsageLogRepository)(nil).Create), arg0, arg1)
}

// GetDailyUsageByUserID mocks base method.
func (m *MockUsageLogRepository) GetDailyUsageByUserID(arg0 context.Context, arg1 int64, arg2 int) ([]domain.DailyUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyUsageByUserID", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.DailyUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyUsageByUserID indicates an expected call of GetDailyUsageByUserID.
func (mr *MockUsageLogRepositoryMockRecorder) GetDailyUsageByUserID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyUsageByUserID", reflect.TypeOf((*MockUsageLogRepository)(nil).GetDailyUsageByUserID), arg0, arg1, arg2)
}

// GetGlobalStats mocks base method.
func (m *MockUsageLogRepository) GetGlobalStats(arg0 context.Context) (*domain.UsageStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalStats", arg0)
	ret0, _ := ret[0].(*domain.UsageStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalStats indicates an expected call of GetGlobalStats.
func (mr *MockUsageLogRepositoryMockRecorder) GetGlobalStats(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalStats", reflect.TypeOf((*MockUsageLogRepository)(nil).GetGlobalStats), arg0)
}

// GetStatsByUserID mocks base method.
func (m *MockUsageLogRepository) GetStatsByUserID(arg0 context.Context, arg1 int64) (*domain.UsageStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatsByUserID", arg0, arg1)
	ret0, _ := ret[0].(*domain.UsageStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatsByUserID indicates an expected call of GetStatsByUserID.
func (mr *MockUsageLogRepositoryMockRecorder) GetStatsByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatsByUserID", reflect.TypeOf((*MockUsageLogRepository)(nil).GetStatsByUserID), arg0, arg1)
}

// GetTopAPIKeys mocks base method.
func (m *MockUsageLogRepository) GetTopAPIKeys(arg0 context.Context, arg1, arg2 int) ([]domain.UsageLeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopAPIKeys", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.UsageLeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopAPIKeys indicates an expected call of GetTopAPIKeys.
func (mr *MockUsageLogRepositoryMockRecorder) GetTopAPIKeys(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopAPIKeys", reflect.TypeOf((*MockUsageLogRepository)(nil).GetTopAPIKeys), arg0, arg1, arg2)
}

// GetTopClientIPs mocks base method.
func (m *MockUsageLogRepository) GetTopClientIPs(arg0 context.Context, arg1, arg2 int) ([]domain.UsageLeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopClientIPs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.UsageLeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopClientIPs indicates an expected call of GetTopClientIPs.
func (mr *MockUsageLogRepositoryMockRecorder) GetTopClientIPs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopClientIPs", reflect.TypeOf((*MockUsageLogRepository)(nil).GetTopClientIPs), arg0, arg1, arg2)
}

// GetTopUsers mocks base method.
func (m *MockUsageLogRepository) GetTopUsers(arg0 context.Context, arg1, arg2 int) ([]domain.UsageLeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopUsers", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.UsageLeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopUsers indicates an expected call of GetTopUsers.
func (mr *MockUsageLogRepositoryMockRecorder) GetTopUsers(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopUsers", reflect.TypeOf((*MockUsageLogRepository)(nil).GetTopUsers), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockUsageLogRepository) List(arg0 context.Context, arg1, arg2 int, arg3 map[string]interface{}) ([]*domain.UsageLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.UsageLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockUsageLogRepositoryMockRecorder) List(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUsageLogRepository)(nil).List), arg0, arg1, arg2, arg3)
}

// MockAPIKeyRepository is a mock of APIKeyRepository interface.
type MockAPIKeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyRepositoryMockRecorder
}

// MockAPIKeyRepositoryMockRecorder is the mock recorder for MockAPIKeyRepository.
type MockAPIKeyRepositoryMockRecorder struct {
	mock *MockAPIKeyRepository
}

// NewMockAPIKeyRepository creates a new mock instance.
func NewMockAPIKeyRepository(ctrl *gomock.Controller) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{ctrl: ctrl}
	mock.recorder = &MockAPIKeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAPIKeyRepository) Create(arg0 context.Context, arg1 *domain.APIKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAPIKeyRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAPIKeyRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockAPIKeyRepository) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAPIKeyRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAPIKeyRepository)(nil).Delete), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockAPIKeyRepository) GetByID(arg0 context.Context, arg1 int64) (*domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAPIKeyRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAPIKeyRepository)(nil).GetByID), arg0, arg1)
}

// GetByKey mocks base method.
func (m *MockAPIKeyRepository) GetByKey(arg0 context.Context, arg1 string) (*domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", arg0, arg1)
	ret0, _ := ret[0].(*domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockAPIKeyRepositoryMockRecorder) GetByKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockAPIKeyRepository)(nil).GetByKey), arg0, arg1)
}

// IncrementUsage mocks base method.
func (m *MockAPIKeyRepository) IncrementUsage(arg0 context.Context, arg1 int64, arg2 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUsage", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementUsage indicates an expected call of IncrementUsage.
func (mr *MockAPIKeyRepositoryMockRecorder) IncrementUsage(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUsage", reflect.TypeOf((*MockAPIKeyRepository)(nil).IncrementUsage), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockAPIKeyRepository) List(arg0 context.Context) ([]domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAPIKeyRepositoryMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAPIKeyRepository)(nil).List), arg0)
}

// ListByUserID mocks base method.
func (m *MockAPIKeyRepository) ListByUserID(arg0 context.Context, arg1 int64) ([]domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", arg0, arg1)
	ret0, _ := ret[0].([]domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockAPIKeyRepositoryMockRecorder) ListByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockAPIKeyRepository)(nil).ListByUserID), arg0, arg1)
}

// Update mocks base method.
func (m *MockAPIKeyRepository) Update(arg0 context.Context, arg1 *domain.APIKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAPIKeyRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAPIKeyRepository)(nil).Update), arg0, arg1)
}

// UpdateLastUsed mocks base method.
func (m *MockAPIKeyRepository) UpdateLastUsed(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastUsed", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastUsed indicates an expected call of UpdateLastUsed.
func (mr *MockAPIKeyRepositoryMockRecorder) UpdateLastUsed(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUsed", reflect.TypeOf((*MockAPIKeyRepository)(nil).UpdateLastUsed), arg0, arg1)
}

// Validate mocks base method.
func (m *MockAPIKeyRepository) Validate(arg0 context.Context, arg1 string) (bool, *domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*domain.APIKey)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Validate indicates an expected call of Validate.
func (mr *MockAPIKeyRepositoryMockRecorder) Validate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockAPIKeyRepository)(nil).Validate), arg0, arg1)
}
