// Code generated by MockGen. DO NOT EDIT.
// Source: ./gateway.go

// Package gatewaymocks is a generated GoMock package.
package gatewaymocks

import (
	domain "ai-gateway/internal/domain"
	providers "ai-gateway/internal/providers"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGatewayService is a mock of GatewayService interface.
type MockGatewayService struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayServiceMockRecorder
}

// MockGatewayServiceMockRecorder is the mock recorder for MockGatewayService.
type MockGatewayServiceMockRecorder struct {
	mock *MockGatewayService
}

// NewMockGatewayService creates a new mock instance.
func NewMockGatewayService(ctrl *gomock.Controller) *MockGatewayService {
	mock := &MockGatewayService{ctrl: ctrl}
	mock.recorder = &MockGatewayServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayService) EXPECT() *MockGatewayServiceMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockGatewayService) Chat(ctx context.Context, req *domain.ChatRequest) (*domain.ChatResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat", ctx, req)
	ret0, _ := ret[0].(*domain.ChatResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chat indicates an expected call of Chat.
func (mr *MockGatewayServiceMockRecorder) Chat(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockGatewayService)(nil).Chat), ctx, req)
}

// ChatStream mocks base method.
func (m *MockGatewayService) ChatStream(ctx context.Context, req *domain.ChatRequest) (<-chan domain.StreamDelta, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatStream", ctx, req)
	ret0, _ := ret[0].(<-chan domain.StreamDelta)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ChatStream indicates an expected call of ChatStream.
func (mr *MockGatewayServiceMockRecorder) ChatStream(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatStream", reflect.TypeOf((*MockGatewayService)(nil).ChatStream), ctx, req)
}

// GetProvider mocks base method.
func (m *MockGatewayService) GetProvider(model string) (providers.Provider, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvider", model)
	ret0, _ := ret[0].(providers.Provider)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetProvider indicates an expected call of GetProvider.
func (mr *MockGatewayServiceMockRecorder) GetProvider(model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvider", reflect.TypeOf((*MockGatewayService)(nil).GetProvider), model)
}

// ListModels mocks base method.
func (m *MockGatewayService) ListModels(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModels", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModels indicates an expected call of ListModels.
func (mr *MockGatewayServiceMockRecorder) ListModels(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModels", reflect.TypeOf((*MockGatewayService)(nil).ListModels), ctx)
}

// Reload mocks base method.
func (m *MockGatewayService) Reload(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reload", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reload indicates an expected call of Reload.
func (mr *MockGatewayServiceMockRecorder) Reload(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reload", reflect.TypeOf((*MockGatewayService)(nil).Reload), ctx)
}
