// Code generated by MockGen. DO NOT EDIT.
// Source: ./wallet.go

// Package walletmocks is a generated GoMock package.
package walletmocks

import (
	domain "ai-gateway/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Deduct mocks base method.
func (m *MockService) Deduct(ctx context.Context, userID int64, inputTokens, outputTokens int, modelName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deduct", ctx, userID, inputTokens, outputTokens, modelName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deduct indicates an expected call of Deduct.
func (mr *MockServiceMockRecorder) Deduct(ctx, userID, inputTokens, outputTokens, modelName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deduct", reflect.TypeOf((*MockService)(nil).Deduct), ctx, userID, inputTokens, outputTokens, modelName)
}

// GetBalance mocks base method.
func (m *MockService) GetBalance(ctx context.Context, userID int64) (*domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(*domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockServiceMockRecorder) GetBalance(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockService)(nil).GetBalance), ctx, userID)
}

// GetTransactions mocks base method.
func (m *MockService) GetTransactions(ctx context.Context, userID int64, page, size int) ([]domain.WalletTransaction, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactions", ctx, userID, page, size)
	ret0, _ := ret[0].([]domain.WalletTransaction)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTransactions indicates an expected call of GetTransactions.
func (mr *MockServiceMockRecorder) GetTransactions(ctx, userID, page, size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockService)(nil).GetTransactions), ctx, userID, page, size)
}

// HasBalance mocks base method.
func (m *MockService) HasBalance(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasBalance", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasBalance indicates an expected call of HasBalance.
func (mr *MockServiceMockRecorder) HasBalance(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasBalance", reflect.TypeOf((*MockService)(nil).HasBalance), ctx, userID)
}

// TopUp mocks base method.
func (m *MockService) TopUp(ctx context.Context, userID int64, amount float64, referenceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopUp", ctx, userID, amount, referenceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TopUp indicates an expected call of TopUp.
func (mr *MockServiceMockRecorder) TopUp(ctx, userID, amount, referenceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopUp", reflect.TypeOf((*MockService)(nil).TopUp), ctx, userID, amount, referenceID)
}
