// Code generated by MockGen. DO NOT EDIT.
// Source: ./usage.go

// Package usagemocks is a generated GoMock package.
package usagemocks

import (
	domain "ai-gateway/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetGlobalDailyUsage mocks base method.
func (m *MockService) GetGlobalDailyUsage(ctx context.Context, days int) ([]domain.DailyUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalDailyUsage", ctx, days)
	ret0, _ := ret[0].([]domain.DailyUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalDailyUsage indicates an expected call of GetGlobalDailyUsage.
func (mr *MockServiceMockRecorder) GetGlobalDailyUsage(ctx, days interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalDailyUsage", reflect.TypeOf((*MockService)(nil).GetGlobalDailyUsage), ctx, days)
}

// GetGlobalStats mocks base method.
func (m *MockService) GetGlobalStats(ctx context.Context) (*domain.UsageStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalStats", ctx)
	ret0, _ := ret[0].(*domain.UsageStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalStats indicates an expected call of GetGlobalStats.
func (mr *MockServiceMockRecorder) GetGlobalStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalStats", reflect.TypeOf((*MockService)(nil).GetGlobalStats), ctx)
}

// GetLeaderboard mocks base method.
func (m *MockService) GetLeaderboard(ctx context.Context, dimension string, limit, days int) ([]domain.UsageLeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeaderboard", ctx, dimension, limit, days)
	ret0, _ := ret[0].([]domain.UsageLeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeaderboard indicates an expected call of GetLeaderboard.
func (mr *MockServiceMockRecorder) GetLeaderboard(ctx, dimension, limit, days interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeaderboard", reflect.TypeOf((*MockService)(nil).GetLeaderboard), ctx, dimension, limit, days)
}

// ListLogs mocks base method.
func (m *MockService) ListLogs(ctx context.Context, page, pageSize int, filters map[string]interface{}) ([]*domain.UsageLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLogs", ctx, page, pageSize, filters)
	ret0, _ := ret[0].([]*domain.UsageLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLogs indicates an expected call of ListLogs.
func (mr *MockServiceMockRecorder) ListLogs(ctx, page, pageSize, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLogs", reflect.TypeOf((*MockService)(nil).ListLogs), ctx, page, pageSize, filters)
}

// LogRequest mocks base method.
func (m *MockService) LogRequest(ctx context.Context, log *domain.UsageLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogRequest", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogRequest indicates an expected call of LogRequest.
func (mr *MockServiceMockRecorder) LogRequest(ctx, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogRequest", reflect.TypeOf((*MockService)(nil).LogRequest), ctx, log)
}
