// Code generated by MockGen. DO NOT EDIT.
// Source: ./apikey.go

// Package apikeymocks is a generated GoMock package.
package apikeymocks

import (
	domain "ai-gateway/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, userID int64, name string, enabled *bool, quota *float64, expiresAt *time.Time) (*domain.APIKey, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, name, enabled, quota, expiresAt)
	ret0, _ := ret[0].(*domain.APIKey)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, userID, name, enabled, quota, expiresAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, userID, name, enabled, quota, expiresAt)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, userID, keyID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, keyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, userID, keyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, userID, keyID)
}

// DeleteByID mocks base method.
func (m *MockService) DeleteByID(ctx context.Context, keyID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, keyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockServiceMockRecorder) DeleteByID(ctx, keyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockService)(nil).DeleteByID), ctx, keyID)
}

// IncrementUsage mocks base method.
func (m *MockService) IncrementUsage(ctx context.Context, apiKeyID int64, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUsage", ctx, apiKeyID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementUsage indicates an expected call of IncrementUsage.
func (mr *MockServiceMockRecorder) IncrementUsage(ctx, apiKeyID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUsage", reflect.TypeOf((*MockService)(nil).IncrementUsage), ctx, apiKeyID, amount)
}

// List mocks base method.
func (m *MockService) List(ctx context.Context) ([]domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx)
}

// ListByUserID mocks base method.
func (m *MockService) ListByUserID(ctx context.Context, userID int64) ([]domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockServiceMockRecorder) ListByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockService)(nil).ListByUserID), ctx, userID)
}

// RecordUsage mocks base method.
func (m *MockService) RecordUsage(ctx context.Context, apiKeyID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordUsage", ctx, apiKeyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordUsage indicates an expected call of RecordUsage.
func (mr *MockServiceMockRecorder) RecordUsage(ctx, apiKeyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordUsage", reflect.TypeOf((*MockService)(nil).RecordUsage), ctx, apiKeyID)
}

// ValidateAPIKey mocks base method.
func (m *MockService) ValidateAPIKey(ctx context.Context, key string) (*domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAPIKey", ctx, key)
	ret0, _ := ret[0].(*domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAPIKey indicates an expected call of ValidateAPIKey.
func (mr *MockServiceMockRecorder) ValidateAPIKey(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAPIKey", reflect.TypeOf((*MockService)(nil).ValidateAPIKey), ctx, key)
}
